name: dev
on:
  pull_request:
  push:
    branches:
      - master
      - phated/ci
env:
  CI: true

jobs:
  test:
    name: Tests for Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20, 22, 24]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - node: 6
            os: ubuntu-latest
          - node: 8
            os: ubuntu-latest
          - node: 10
            os: ubuntu-latest
          - node: 12
            os: ubuntu-latest
          - node: 14
            os: ubuntu-latest
          - node: 6
            os: windows-latest
          - node: 8
            os: windows-latest
          - node: 10
            os: windows-latest
          - node: 12
            os: windows-latest
          - node: 14
            os: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set Node.js version
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}

      - name: Check node version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Install npm dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test
